quarkus:
  datasource:
    username: superheroesadmin
    password: super-heroes-p#ssw0rd-12046
    reactive:
      url: postgresql://super-heroes-db.postgres.database.azure.com:5432/heroes_database?ssl=true&sslmode=require
